export { createDb } from './db/client.js';
export type { Database } from './db/client.js';
export { createCaseDeps } from './db/case-deps.js';
export type { CaseServiceDeps } from './services/cases/case-service.js';
export { createCase, listCases, getCase } from './services/cases/case-service.js';
export { createConsentDeps } from './db/consent-deps.js';
export type { ConsentServiceDeps } from './services/consent/consent-service.js';
export type { CandidateSafeView } from './services/consent/consent-service.js';
export { getCandidateView } from './services/consent/consent-service.js';
export { createDocumentDeps, listDocumentKindsByCase } from './db/document-deps.js';
export type { DocumentServiceDeps } from './services/documents/document-service.js';
export { createTokenVerifier } from './db/token-deps.js';
export { createDocumentStorageFromEnv } from './storage/document-storage.js';
export type { DocumentStorage } from './storage/document-storage.js';
export { uploadDocumentHandler } from './routes/public/documents.js';
export { grantConsentHandler, withdrawConsentHandler } from './routes/public/consent.js';
export { getCandidateHandler } from './routes/public/candidate.js';
export { resolveToken } from './routes/public/token-auth.js';
export { toErrorResponse, AppError } from './http/errors.js';
export type { ApiError } from './http/errors.js';
